<?php
/**
 * @file
 * ms_themes.module file
 */

/**
 * Implements hook_cron().
 *
 * Synchronizes and fetches themes from
 * www.humanitarianresponse.info/api/v1.0/themes on cron.
 */
function ms_themes_cron() {
  ms_themes_fetch_and_sync();
}

/**
 * Fetch and sync countries.
 *
 * Fetch and sync countries from
 * www.humanitarianresponse.info/api/v1.0/themes.
 */
function ms_themes_fetch_and_sync() {
  $languages = array(
    'en',
    'fr',
    'es',
  );
  $installed_languages = array_keys(language_list());

  foreach ($languages as $language) {
    if (in_array($language, $installed_languages)) {
      $url = 'https://www.humanitarianresponse.info/' . $language . '/api/v1.0/themes';

      while (TRUE) {
        $request = drupal_http_request($url);
        if (isset($request->data)) {
          $data = drupal_json_decode($request->data);
          if (empty($data['data'])) {
            return;
          }

          foreach ($data['data'] as $item) {
            if (isset($item['label']) && $item['label'] && isset($item['id']) && $item['id']) {
              $query = new EntityFieldQuery();
              $query->entityCondition('entity_type', 'taxonomy_term');
              $query->entityCondition('bundle', 'ms_themes', '=');
              $query->fieldCondition('field_ms_hrinfo_id', 'value', $item['id'], '=');
              $result = $query->execute();

              $term = new stdClass();
              if (!isset($result['taxonomy_term'])) {
                $vocabularies = taxonomy_vocabulary_get_names();
                $term = (object) array(
                  'vid' => $vocabularies['ms_themes']->vid,
                  'name' => $item['label'],
                  'vocabulary_machine_name' => 'ms_themes',
                );
              }
              else {
                $tid = array_pop($result['taxonomy_term']);
                $term = taxonomy_term_load($tid->tid);
                if ($language != 'en' && !isset($term->translations->data[$language])) {
                  $translation = array(
                    'translate' => 0,
                    'status' => 1,
                    'language' => $language,
                    'source' => 'en',
                  );
                  $handler = entity_translation_get_handler('taxonomy_term', $term);
                  $handler->setTranslation($translation);
                }
              }

              if ($language == 'en') {
                $term->name = $item['label'];
              }
              $term->name_field[$language][0]['value'] = $item['label'];
              $term->field_ms_hrinfo_id[LANGUAGE_NONE][0]['value'] = $item['id'];

              taxonomy_term_save($term);
            }
          }
          if (isset($data['next']) && isset($data['next']['href'])) {
            $url = $data['next']['href'];
          }
          else {
            break;
          }
        }
      }
    }
  }
}
